
-- 1. Create PROFILES table (extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email text,
    full_name text,
    phone text,
    gstin text,
    role text CHECK (role IN ('user', 'admin')) DEFAULT 'user',
    is_banned boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Toggle for Row Level Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- 2. Create PLANS table
CREATE TABLE IF NOT EXISTS public.plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    price numeric NOT NULL DEFAULT 0,
    interval text CHECK (interval IN ('month', 'year', 'lifetime')) DEFAULT 'month',
    features jsonb DEFAULT '[]'::jsonb, -- List of enabled feature keys e.g. ["invoice", "calculator"]
    limits jsonb DEFAULT '{}'::jsonb, -- e.g. {"invoice_count": 100}
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Everyone can read plans" ON public.plans;
CREATE POLICY "Everyone can read plans" ON public.plans FOR SELECT USING (true);

-- 3. Create SUBSCRIPTIONS table
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) NOT NULL,
    plan_id bigint REFERENCES public.plans(id) NOT NULL,
    status text CHECK (status IN ('active', 'trialing', 'past_due', 'canceled', 'expired')) DEFAULT 'active',
    start_date timestamp with time zone DEFAULT now(),
    end_date timestamp with time zone, -- Null means lifetime or auto-renew logic handled elsewhere
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read own subscription" ON public.subscriptions;
CREATE POLICY "Users can read own subscription" ON public.subscriptions 
    FOR SELECT USING (auth.uid() = user_id);

-- 4. Create COUPONS table (Optional but requested)
CREATE TABLE IF NOT EXISTS public.coupons (
    code text PRIMARY KEY,
    discount_type text CHECK (discount_type IN ('percent', 'fixed')),
    discount_value numeric NOT NULL,
    max_uses integer DEFAULT -1, -- -1 for infinite
    used_count integer DEFAULT 0,
    valid_until timestamp with time zone,
    is_active boolean DEFAULT true
);

-- 5. Auto-create Profile on Signup (Trigger)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. Insert Default Plans
INSERT INTO public.plans (name, price, interval, features, limits)
VALUES 
('Free', 0, 'lifetime', '["calculator", "news"]'::jsonb, '{"invoices": 5}'::jsonb),
('Pro Monthly', 199, 'month', '["calculator", "news", "invoice", "reminders", "itc_reconciliation"]'::jsonb, '{"invoices": -1}'::jsonb),
('Pro Yearly', 1999, 'year', '["calculator", "news", "invoice", "reminders", "itc_reconciliation"]'::jsonb, '{"invoices": -1}'::jsonb)
ON CONFLICT DO NOTHING;
