
-- News table to store auto-fetched GST news articles
CREATE TABLE IF NOT EXISTS public.gst_news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id text UNIQUE, -- NewsData.io article_id for dedup
    title text NOT NULL,
    description text,
    content text,
    source_name text,
    source_url text,
    source_icon text,
    image_url text,
    link text,
    category text[] DEFAULT '{}',
    language text DEFAULT 'en',
    country text[] DEFAULT '{}',
    published_at timestamp with time zone,
    fetched_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now()
);

-- Allow public read (app needs to show news)
ALTER TABLE public.gst_news ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read news" ON public.gst_news;
CREATE POLICY "Anyone can read news" ON public.gst_news FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can insert news" ON public.gst_news;
CREATE POLICY "Anyone can insert news" ON public.gst_news FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Anyone can update news" ON public.gst_news;
CREATE POLICY "Anyone can update news" ON public.gst_news FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Anyone can delete news" ON public.gst_news;
CREATE POLICY "Anyone can delete news" ON public.gst_news FOR DELETE USING (true);

-- News fetch log to track when we last fetched
CREATE TABLE IF NOT EXISTS public.news_fetch_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fetched_at timestamp with time zone DEFAULT now(),
    articles_count integer DEFAULT 0,
    status text DEFAULT 'success',
    error_message text
);

ALTER TABLE public.news_fetch_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin can read fetch log" ON public.news_fetch_log;
CREATE POLICY "Admin can read fetch log" ON public.news_fetch_log FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can insert fetch log" ON public.news_fetch_log;
CREATE POLICY "Anyone can insert fetch log" ON public.news_fetch_log FOR INSERT WITH CHECK (true);

-- Indexes for quick lookups
CREATE INDEX IF NOT EXISTS idx_gst_news_published_at ON public.gst_news (published_at DESC);
CREATE INDEX IF NOT EXISTS idx_gst_news_article_id ON public.gst_news (article_id);
