-- Create table if it doesn't exist (basic structure)
CREATE TABLE IF NOT EXISTS public.app_settings (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    gst_rate text DEFAULT '18%'::text NOT NULL,
    gst_description text DEFAULT 'Standard rate for services'::text NOT NULL,
    threshold_amount integer DEFAULT 2000000 NOT NULL,
    threshold_text text DEFAULT '₹20 Lakhs'::text NOT NULL,
    foreign_income_mandatory boolean DEFAULT true NOT NULL,
    guides jsonb DEFAULT '[]'::jsonb NOT NULL,
    disclaimer text DEFAULT 'Disclaimer: This guide is for educational purposes only. GST laws change frequently. Please consult a CA for your specific case.'::text NOT NULL,
    
    CONSTRAINT app_settings_singleton CHECK (id = 1)
);

-- Add new columns safely (idempotent)
DO $$ 
BEGIN 
    ALTER TABLE public.app_settings ADD COLUMN IF NOT EXISTS gst_rules jsonb DEFAULT '[]'::jsonb NOT NULL;
    ALTER TABLE public.app_settings ADD COLUMN IF NOT EXISTS calculator_config jsonb DEFAULT '{"default_margin": 20, "default_tcs": 1.0, "default_gst": 12}'::jsonb NOT NULL;
    ALTER TABLE public.app_settings ADD COLUMN IF NOT EXISTS reminder_config jsonb DEFAULT '[]'::jsonb NOT NULL;
    ALTER TABLE public.app_settings ADD COLUMN IF NOT EXISTS feature_flags jsonb DEFAULT '{"enable_news": true, "enable_tools": true, "enable_calculator": true}'::jsonb NOT NULL;
EXCEPTION
    WHEN duplicate_column THEN NULL;
END $$;

-- Policies: Drop first to ensure clean state
DROP POLICY IF EXISTS "Allow public read access" ON public.app_settings;
DROP POLICY IF EXISTS "Allow authenticated update access" ON public.app_settings;

-- Enable RLS
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- Re-create policies
CREATE POLICY "Allow public read access" ON public.app_settings
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow authenticated update access" ON public.app_settings
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Insert or Update initial data
INSERT INTO public.app_settings (
    id,
    gst_rate,
    gst_description,
    threshold_amount,
    threshold_text,
    foreign_income_mandatory,
    guides,
    disclaimer,
    gst_rules,
    reminder_config
)
VALUES (
    1,
    '18%',
    'Standard rate for services',
    2000000,
    '₹20 Lakhs',
    true,
    -- Guides
    '[
        {"icon": "FileText", "color": "green", "title": "LUT Filing for Export", "desc": "File LUT to claim 0% tax on foreign income."},
        {"icon": "AlertTriangle", "color": "yellow", "title": "Common Mistakes", "desc": "Avoid these 5 errors in your GSTR-1/3B."},
        {"icon": "Receipt", "color": "blue", "title": "Eligible Expenses", "desc": "Claims for gear, rent, and internet costs."}
    ]'::jsonb,
    -- Disclaimer
    'Disclaimer: This guide is for educational purposes only. GST laws change frequently. Please consult a CA for your specific case.',
    -- GST Rules
    '[
        {"id": 1, "name": "Mobile Phone", "category": "Electronics", "hsn": "8517", "gstRate": 18, "cgst": 9, "sgst": 9, "igst": 18, "description": "Smartphones and handheld mobile devices."},
        {"id": 2, "name": "Laptop", "category": "Electronics", "hsn": "8471", "gstRate": 18, "cgst": 9, "sgst": 9, "igst": 18, "description": "Personal computers and laptops."},
        {"id": 3, "name": "Headphones", "category": "Electronics", "hsn": "8518", "gstRate": 18, "cgst": 9, "sgst": 9, "igst": 18, "description": "Wired and wireless headphones/earphones."},
        {"id": 4, "name": "Men''s Cotton Shirt", "category": "Clothing", "hsn": "6205", "gstRate": 5, "cgst": 2.5, "sgst": 2.5, "igst": 5, "description": "Cotton shirts value below Rs. 1000."},
        {"id": 5, "name": "Silk Saree", "category": "Clothing", "hsn": "5007", "gstRate": 5, "cgst": 2.5, "sgst": 2.5, "igst": 5, "description": "Woven fabrics of silk or of silk waste."},
        {"id": 6, "name": "Jeans", "category": "Clothing", "hsn": "6203", "gstRate": 12, "cgst": 6, "sgst": 6, "igst": 12, "description": "Readymade garments value exceeding Rs. 1000."},
        {"id": 7, "name": "Notebooks", "category": "Study", "hsn": "4820", "gstRate": 12, "cgst": 6, "sgst": 6, "igst": 12, "description": "Exercise books, notebooks, registers."},
        {"id": 8, "name": "Pencils & Sharpeners", "category": "Study", "hsn": "9609", "gstRate": 12, "cgst": 6, "sgst": 6, "igst": 12, "description": "Pencils, crayons, and pencil sharpeners."},
        {"id": 9, "name": "Printed Books", "category": "Study", "hsn": "4901", "gstRate": 0, "cgst": 0, "sgst": 0, "igst": 0, "description": "Printed books, brochures, leaflets (Nil Rated)."},
        {"id": 10, "name": "Rice (Branded)", "category": "Food", "hsn": "1006", "gstRate": 5, "cgst": 2.5, "sgst": 2.5, "igst": 5, "description": "Rice put up in a unit container and bearing a registered brand name."},
        {"id": 11, "name": "IT Services", "category": "Services", "hsn": "9983", "gstRate": 18, "cgst": 9, "sgst": 9, "igst": 18, "description": "Information technology consulting and support services."},
        {"id": 12, "name": "Legal Services", "category": "Services", "hsn": "9982", "gstRate": 18, "cgst": 9, "sgst": 9, "igst": 18, "description": "Legal advisory and representation services."},
        {"id": 13, "name": "Construction (Res.)", "category": "Build", "hsn": "9954", "gstRate": 5, "cgst": 2.5, "sgst": 2.5, "igst": 5, "description": "Construction of residential apartments (Non-Affordable)."},
        {"id": 14, "name": "Cement", "category": "Build", "hsn": "2523", "gstRate": 28, "cgst": 14, "sgst": 14, "igst": 28, "description": "Portland cement, aluminous cement, slag cement."},
        {"id": 15, "name": "Paracetamol", "category": "Health", "hsn": "3004", "gstRate": 12, "cgst": 6, "sgst": 6, "igst": 12, "description": "Medicaments consisting of mixed or unmixed products."}
    ]'::jsonb,
    -- Reminder Config
    '[
        {"id": 1, "code": "GSTR-1", "name": "Monthly Return", "priority": "MEDIUM", "dueDate": "11th of Month", "lateFee": "₹60/day", "enabled": true, "frequency": "Monthly", "icon": "file"},
        {"id": 2, "code": "GSTR-3B", "name": "Quarterly", "priority": "HIGH", "dueDate": "24th of Month", "lateFee": "₹50/day", "enabled": true, "frequency": "Quarterly", "icon": "alert"},
        {"id": 3, "code": "GSTR-9", "name": "Annual Return", "priority": "LOW", "dueDate": "31st Dec", "lateFee": "₹200/day", "enabled": false, "frequency": "Annual", "icon": "calendar"}
    ]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    gst_rules = EXCLUDED.gst_rules,
    reminder_config = EXCLUDED.reminder_config,
    -- Also update other fields if they were NULL (optional, but good for migrations)
    calculator_config = CASE WHEN app_settings.calculator_config IS NULL THEN EXCLUDED.calculator_config ELSE app_settings.calculator_config END,
    feature_flags = CASE WHEN app_settings.feature_flags IS NULL THEN EXCLUDED.feature_flags ELSE app_settings.feature_flags END;
